import './global.css';
import { ToastContainer } from 'react-toastify';
export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <ToastContainer
          position="top-center"
          autoClose={2000}
          hideProgressBar
          pauseOnFocusLoss={false}
        />
        {children}
      </body>
    </html>
  );
}
